Update jenkinsfile

diff --git a/jenkinsfile b/jenkinsfile
--- a/jenkinsfile
+++ b/jenkinsfile
@@ -18,7 +18,7 @@ pipeline {
             steps {
                 // Check if Python3 and pip3 are installed
                 sh '''
-                if ! command -v python3 &> /dev/null; then
+                if ! command -v /usr/bin/python3 &> /dev/null; then
                     echo "Python3 not installed"
                     exit 1
                 fi
@@ -30,6 +30,26 @@ pipeline {
             }
         }
 
+        stage('Install Pip') {
+            steps {
+                sh '''
+                if ! command -v pip3 &> /dev/null; then
+                    echo "pip3 not found, installing..."
+                    curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
+                    /usr/bin/python3 get-pip.py
+                fi
+                '''
+            }
+        }
+
+        stage('Install Frontend Dependencies') {
+            steps {
+                dir('society/Frontend/myapp') {
+                    sh 'npm install'
+                }
+            }
+        }
+
         stage('Setup Python Virtual Env') {
             steps {
                 dir('society/Backend') {
@@ -38,14 +58,6 @@ pipeline {
                     source venv/bin/activate
                     pip install -r requirements.txt
                     '''
-                }
-            }
-        }
-
-        stage('Install Frontend Dependencies') {
-            steps {
-                dir('society/Frontend/myapp') {
-                    sh 'npm install'
                 }
             }
         }
